### ISSUE TITLE
Connecting to MongoDB

### ISSUE THREAD

**Issue by Piyush-onGIT** [Technocracy-NITRR/TC_Backend#1]
# Describing the issue

Our first task is to connect this backend to a database. We are going to use MongoDB as our database. After connecting, we have to create three endpoints for registering in three of the sample events -> E1, E2, and E3.

Inside the database, we have three collections -> E1, E2, and E3. We will store the details of the users in the respective events using ExpressJS APIs. So our task is to create such APIs.

User details to be stored in the events:
E1: Name, Branch, Semester, Roll Number
E2: Name, Branch, Semester, Github Username
E3: Name, Branch, Semester, PUBG Username

**Comment by Piyush-onGIT** [comment]
@probot-codes Your task is to connect the ExpressJS API to MongoDB and create an endpoint for registration in the event E1 only.

**Comment by Piyush-onGIT** [comment]
@student-mayank 
You have to wait for Prabhat, as soon he connects to the MongoDB database, you have to create the endpoints for events E2 and E3.

**Comment by probot-codes** [comment]
Sir, MongoDB connected to the API and endpoint for the event E1 created
